#!/bin/bash
cmd=$1
arg=$2

case $cmd in 
    init)
    if [ "$arg" == "venv" ]; then
        python3 -m venv ./tsh/venv
        source tsh/venv/bin/activate
        pip install questionary
    fi
;;
    run)
source tsh/venv/bin/activate
python3 ./tsh/tsh.py $arg 
;;
    run-poetry)
poetry run python tsh.py $arg
;;
    repl)
poetry run python ./src/repl.py
esac